name: Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Coolpad-Note-3-Lite-Development/android_kernel_xiaomi_onc
          ref: test

      - name: Setup
        run: |
          bash -c "$(wget -O- https://github.com/crevanth/kernel_builder/raw/main/.github/workflows/setup.sh)"

      - name: Compile
        run: |
          bash -c "$(wget -O- https://github.com/crevanth/kernel_builder/raw/main/.github/workflows/compile.sh)"

      - name: Make zip and send
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          bash -c "$(wget -O- https://github.com/crevanth/kernel_builder/raw/main/.github/workflows/send2tg.sh)"
